### ISSUE TITLE
Consider using bcryptjs

### ISSUE THREAD

**Issue by fredrikekelund** [morungos/passport-local-htpasswd#1]
Thanks for a handy module! It's a logical abstraction, and it saved me some typing.

One thing I noted however was the fact that it depends on [bcrypt](https://www.npmjs.com/package/bcrypt), which is a binary module. [bcryptjs](https://www.npmjs.com/package/bcryptjs) is API compatible, but pure JS, which makes it more portable and faster to install. Would you consider changing the dependency from bcrypt to bcryptjs?

**Comment by morungos** [comment]
Good suggestion. I just checked the pages and it seems it's only about 20% slower for my typical use case (10 rounds), so given the misery `bcrypt` deployments are inflicting on me, I might well make this change across my stack as well as here. 

I'll get a new version out today if it'll help.

**Comment by fredrikekelund** [comment]
Great! No stress on my part, but of course, would it's always nice with speedy updates 🏎

**Comment by morungos** [comment]
Resolved in `0.1.1`, just pushed

**Comment by fredrikekelund** [comment]
Fantastic, thanks!
